### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by ibakayoko** [sdruckerfig/Ext-JS-6-Bootcamp-In-a-Book#1]
Got the book at senchaCon. I am not able to build the app.

Administrators-MacBook-Pro:final ixb$ sencha app refresh
Sencha Cmd v6.2.0.103
[INF] Processing Build Descriptor : classic
[INF] Loading app json manifest...
[INF] Appending content to /Users/ixb/SenchaDev/final/bootstrap.js
[INF] Writing content to /Users/ixb/SenchaDev/final/classic.json
[INF] Processing Build Descriptor : modern
[INF] Loading app json manifest...
[ERR] Failed to resolve dependency Ext.form.field.TextArea for file Ext.ux.form.TinyMCETextArea
[ERR] 
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.ExNotFound: Unknown definition for dependency : Ext.form.field.TextArea
[ERR] 
[ERR] Total time: 2 seconds
[ERR] The following error occurred while executing this line:
/Users/ixb/bin/Sencha/Cmd/6.2.0.103/plugins/ext/current/plugin.xml:444: The following error occurred while executing this line:
/Users/ixb/SenchaDev/final/.sencha/app/build-impl.xml:380: The following error occurred while executing this line:
/Users/ixb/SenchaDev/final/.sencha/app/init-impl.xml:384: com.sencha.exceptions.ExNotFound: Unknown definition for dependency : Ext.form.field.TextArea

**Comment by sdruckerfig** [comment]
Yeah, it's fine. You're only concerned with building the classic version, which does complete. You can avoid building the modern app by using the following command:

sencha app build classic

**Comment by ibakayoko** [comment]
sencha app build classic
Works. Thank you
